import { DEFAULT_LANG } from './sources.js';

export const DIGEST_SYSTEM = `You are a software archaeologist. You read the design record of a
repository — specifications, implementation plans, decision records — and distil each document
into a dense digest that a later pass will merge into one reference document.

Rules:
- Never invent. Every claim must come from the documents you were given.
- Keep the decisions and their stated rationale; drop the prose, the task checklists and the
  step-by-step implementation choreography.
- Note explicitly when a document supersedes, contradicts or revisits an earlier one.
- Cite the source path for every section you emit.
- Answer with Markdown only — no preamble, no closing remarks.

For each document emit:

### <title> (<path>, <kind>, <date or "undated">)
- **Subject**: one sentence.
- **Decisions**: bullet per decision, each as "decision — rationale (as stated)".
- **Constraints and invariants**: rules the codebase must keep holding; omit the heading if none.
- **Vocabulary**: domain terms the document introduces, with their meaning; omit if none.
- **Components**: the files, modules or services it creates or changes; omit if none.
- **Status signals**: anything marking the document as superseded, abandoned, partially shipped
  or still open; omit if none.`;

export const SYNTHESIS_SYSTEM = `You write retro-documentation: a single reference document
reconstructed from a repository's design record, written to be read by an AI coding agent that is
about to change that repository. It is not a tutorial and not a changelog.

Rules:
- Work only from the digests and repository context you are given. Never invent an API, a file or
  a decision. Where the record is silent, say so instead of guessing.
- Prefer the recent over the old: when two documents conflict, state the current answer, then note
  the earlier one under drift.
- Be specific: name real paths, real commands, real module names.
- Write constraints as imperatives an agent can check itself against.
- Keep every section; write "The design record says nothing about this." under a section rather
  than dropping it.
- Start at heading level 2. Do not repeat the document title, do not add a preamble, and do not
  close with a summary.

Structure, in this order:

## Orientation
What the repository is, who it serves, and the shape of a change to it.

## Glossary
Domain terms an agent must use correctly, one per line as "**term** — meaning".

## Architecture as designed
Components, their responsibilities and how they fit together. Name the directories.

## Decision log
A table: Decision | Rationale | Where it lives | Source. Newest first. One row per decision that
still holds.

## Invariants
Numbered rules the codebase must keep holding, each with the source that established it.

## How work gets done here
The workflows the record describes — testing, review, release, conventions.

## Drift and superseded decisions
Decisions later reversed or overtaken, and anything the record describes that may no longer match
the code. Say plainly that this is the risky part of the document.

## Open questions
What the record leaves undecided, and what an agent should ask a human about before changing.`;

export function buildDigestPrompt(batch) {
  const documents = batch
    .map(
      (source) =>
        `<document path="${source.path}" kind="${source.kind}" date="${source.date ?? 'unknown'}" title="${source.title}">\n${source.text}\n</document>`,
    )
    .join('\n\n');
  return `Digest the following ${batch.length} document(s) from the repository's design record.\n\n${documents}`;
}

export function buildSynthesisPrompt({ context, digests, lang = DEFAULT_LANG, sources = [] }) {
  const inventory = sources
    .map((source) => `- ${source.path} — ${source.title} (${source.kind}, ${source.date ?? 'undated'})`)
    .join('\n');
  return `Write the retro-documentation of the repository "${context.name}" in ${lang}.

<repository>
name: ${context.name}
description: ${context.description || 'none declared'}
top-level entries: ${context.entries.join(', ') || 'unknown'}
</repository>

<readme>
${context.readme || 'No README found.'}
</readme>

<design-record-inventory>
${inventory || 'none'}
</design-record-inventory>

<digests>
${digests.join('\n\n')}
</digests>`;
}

export function renderOutput({ body, context, sources, generator, generatedAt }) {
  const index = sources
    .map((source) => `| ${source.date ?? '—'} | ${source.kind} | ${source.title.replace(/\|/g, '\\|')} | \`${source.path}\` |`)
    .join('\n');
  return `<!-- Generated by maggie retro-doc. Do not edit by hand: regenerate it. -->

# Retro-documentation — ${context.name}

> Reconstructed from ${sources.length} design document(s) by \`${generator}\` on ${generatedAt}.
> It describes the repository **as designed**, not as it stands today: the code is the
> authority, this is the intent behind it. Regenerate after a design change, from
> the command line (\`npm run retro-doc\`) or from the board's Retro-documentation
> panel.

${body.trim()}

## Source index

| Date | Kind | Title | Path |
|---|---|---|---|
${index}
`;
}
