import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  DIGEST_SYSTEM,
  DOMAIN_SYSTEM,
  OVERVIEW_SYSTEM,
  PLAN_SYSTEM,
  SYNTHESIS_SYSTEM,
  buildDigestPrompt,
  buildDomainPrompt,
  buildOverviewPrompt,
  buildPlanPrompt,
  buildSynthesisPrompt,
  renderDomain,
  renderIndex,
  renderOutput,
} from '../src/prompts.js';

test('buildDigestPrompt wraps each document with its path, kind and date', () => {
  const prompt = buildDigestPrompt([
    { path: 'specs/a.md', kind: 'spec', date: '2026-06-14', title: 'A', text: 'body A' },
    { path: 'plans/b.md', kind: 'plan', date: null, title: 'B', text: 'body B' },
  ]);
  assert.match(prompt, /Digest the following 2 document\(s\)/);
  assert.match(prompt, /<document path="specs\/a.md" kind="spec" date="2026-06-14" title="A">\nbody A\n<\/document>/);
  assert.match(prompt, /date="unknown"/);
});

test('buildSynthesisPrompt carries the language, the repository context and the source inventory', () => {
  const prompt = buildSynthesisPrompt({
    context: { name: 'maggie', description: 'd', entries: ['apps/', 'libs/'], readme: '# maggie' },
    digests: ['### A digest'],
    lang: 'français',
    sources: [{ path: 'specs/a.md', title: 'A', kind: 'spec', date: '2026-06-14' }],
  });
  assert.match(prompt, /retro-documentation of the repository "maggie" in français/);
  assert.match(prompt, /top-level entries: apps\/, libs\//);
  assert.match(prompt, /- specs\/a.md — A \(spec, 2026-06-14\)/);
  assert.match(prompt, /### A digest/);
});

test('buildSynthesisPrompt says so rather than lying when the repository has no README', () => {
  const prompt = buildSynthesisPrompt({
    context: { name: 'x', description: '', entries: [], readme: '' },
    digests: [],
    sources: [],
  });
  assert.match(prompt, /No README found\./);
  assert.match(prompt, /description: none declared/);
});

test('renderOutput frames the body with a regeneration warning and a source index', () => {
  const markdown = renderOutput({
    body: '## Orientation\n\nIt syncs skills.',
    context: { name: 'maggie' },
    sources: [
      { path: 'specs/a.md', title: 'A | with pipe', kind: 'spec', date: '2026-06-14' },
      { path: 'plans/b.md', title: 'B', kind: 'plan', date: null },
    ],
    generator: 'claude-opus-5',
    generatedAt: '2026-09-13',
  });
  assert.match(markdown, /^<!-- Generated by maggie retro-doc\./);
  assert.match(markdown, /# Retro-documentation — maggie/);
  assert.match(markdown, /Reconstructed from 2 design document\(s\) by `claude-opus-5` on 2026-09-13/);
  assert.match(markdown, /## Orientation/);
  assert.match(markdown, /\| 2026-06-14 \| spec \| A \\\| with pipe \| `specs\/a.md` \|/);
  assert.match(markdown, /\| — \| plan \| B \| `plans\/b.md` \|/);
});

test('the system prompts forbid inventing, and pin the structure the document must have', () => {
  assert.match(DIGEST_SYSTEM, /Never invent/);
  assert.match(DIGEST_SYSTEM, /Cite the source path/);
  for (const heading of ['## Orientation', '## Glossary', '## Architecture as designed', '## Decision log',
    '## Invariants', '## How work gets done here', '## Drift and superseded decisions', '## Open questions']) {
    assert.ok(SYNTHESIS_SYSTEM.includes(heading), `the synthesis prompt asks for ${heading}`);
  }
  assert.match(SYNTHESIS_SYSTEM, /Never invent/);
});

test('buildSynthesisPrompt defaults to English when no language is asked for', () => {
  const prompt = buildSynthesisPrompt({
    context: { name: 'x', description: '', entries: [], readme: '' },
    digests: [],
  });
  assert.match(prompt, /in English/);
});

const context = { name: 'maggie', description: 'sync skills', entries: ['apps/', 'libs/'], readme: '# maggie' };
const promptSources = [
  { path: 'specs/sync.md', title: 'Sync design', kind: 'spec', date: '2026-01-01' },
  { path: 'specs/board.md', title: 'Board design', kind: 'spec', date: '2026-02-01' },
];
const domains = [
  { slug: 'skill-sync', title: 'Skill sync', summary: 'Rendering skills.', sources: ['specs/sync.md'] },
  { slug: 'board', title: 'Status board', summary: 'The dashboard.', sources: ['specs/board.md'] },
];

test('the planning prompt asks for JSON only, and hands over the whole inventory', () => {
  assert.match(PLAN_SYSTEM, /Answer with a JSON array and nothing else/);
  assert.match(PLAN_SYSTEM, /Between 2 and 8 domains/);
  const prompt = buildPlanPrompt({ context, digests: ['### A digest'], sources: promptSources });
  assert.match(prompt, /Split the design record of the repository "maggie"/);
  assert.match(prompt, /- specs\/sync.md — Sync design \(spec, 2026-01-01\)/);
  assert.match(prompt, /### A digest/);
});

test('the domain prompt scopes the model to one domain and names the others', () => {
  assert.match(DOMAIN_SYSTEM, /Write about the named domain only/);
  const prompt = buildDomainPrompt({ context, domain: domains[0], domains, digests: ['d'], sources: promptSources, lang: 'français' });
  assert.match(prompt, /Write the "Skill sync" page .* in français/);
  assert.match(prompt, /<this-domain-sources>\n- specs\/sync.md — Sync design/);
  assert.match(prompt, /<other-domains>\n- Status board \(board.md\)/);
  assert.ok(!prompt.includes('- specs/board.md — Board design'), 'another domain’s sources are not listed as this one’s');
});

test('the domain prompt says so rather than lying when a domain lists no source', () => {
  const prompt = buildDomainPrompt({
    context,
    domain: { slug: 'x', title: 'X', summary: '', sources: ['gone.md'] },
    domains: [{ slug: 'x', title: 'X', summary: '', sources: [] }],
    digests: [],
    sources: promptSources,
  });
  assert.match(prompt, /none listed — work from the digests/);
  assert.match(prompt, /summary: none given/);
  assert.match(prompt, /<other-domains>\nnone/);
});

test('the front-page prompt lists the domains it must link, and keeps the cross-cutting sections', () => {
  assert.match(OVERVIEW_SYSTEM, /## Glossary/);
  assert.match(OVERVIEW_SYSTEM, /## Invariants that cut across domains/);
  assert.match(OVERVIEW_SYSTEM, /Do not document the domains one by one/);
  const prompt = buildOverviewPrompt({ context, digests: ['d'], domains });
  assert.match(prompt, /- Skill sync \(skill-sync\) — Rendering skills\./);
  assert.match(prompt, /in English/);
});

test('buildOverviewPrompt says when a domain has no summary', () => {
  const prompt = buildOverviewPrompt({ context, digests: [], domains: [{ slug: 'x', title: 'X', summary: '', sources: [] }] });
  assert.match(prompt, /- X \(x\) — no summary/);
});

test('the front page carries the domain table, the body and the whole source index', () => {
  const markdown = renderIndex({
    body: '## Orientation\n\nIt syncs skills.',
    context,
    domains,
    sources: promptSources,
    generator: 'claude-opus-5',
    generatedAt: '2026-09-14',
  });
  assert.match(markdown, /^<!-- Generated by maggie retro-doc\./);
  assert.match(markdown, /# Retro-documentation — maggie/);
  assert.match(markdown, /\| \[Skill sync\]\(skill-sync.md\) \| Rendering skills\. \| 1 \|/);
  assert.match(markdown, /## Orientation/);
  assert.match(markdown, /\| 2026-02-01 \| spec \| Board design \| `specs\/board.md` \|/);
});

test('a domain page links back and indexes only its own sources', () => {
  const markdown = renderDomain({
    body: '## What it does\n\nRenders skills.',
    context,
    domain: domains[0],
    sources: promptSources,
    generator: 'GitHub Copilot CLI',
    generatedAt: '2026-09-14',
  });
  assert.match(markdown, /# Skill sync — maggie/);
  assert.match(markdown, /\[← Retro-documentation\]\(README.md\)/);
  assert.match(markdown, /reconstructed from 1 design document\(s\) by\n> `GitHub Copilot CLI`/);
  assert.match(markdown, /`specs\/sync.md`/);
  assert.ok(!markdown.includes('specs/board.md'), 'another domain’s sources stay out of this page');
});

test('the prompts say "none" rather than leaving a hole when the repository declares nothing', () => {
  const bare = { name: 'bare', description: '', entries: [], readme: '' };
  const plan = buildPlanPrompt({ context: bare, digests: [], sources: [] });
  assert.match(plan, /description: none declared/);
  assert.match(plan, /top-level entries: unknown/);
  assert.match(plan, /<design-record-inventory>\nnone/);

  const overview = buildOverviewPrompt({ context: bare, digests: [], domains: [] });
  assert.match(overview, /description: none declared/);
  assert.match(overview, /top-level entries: unknown/);
  assert.match(overview, /No README found\./);
});

test('a domain with no summary leaves the table cell empty rather than printing "undefined"', () => {
  const markdown = renderIndex({
    body: 'body',
    context: { name: 'x' },
    domains: [{ slug: 'x', title: 'X', sources: [] }],
    sources: [],
    generator: 'g',
    generatedAt: '2026-09-14',
  });
  assert.match(markdown, /\| \[X\]\(x.md\) \| {2}\| 0 \|/);
});

test('a title or summary that would break a table row is escaped, backslash first', () => {
  const nasty = [{ path: 'specs/a.md', title: 'Windows path C:\\ | and a pipe', kind: 'spec', date: '2026-01-01' }];
  const row = renderIndex({
    body: 'body',
    context: { name: 'x' },
    domains: [{ slug: 'd', title: 'A | B', summary: 'ends with a backslash \\', sources: ['specs/a.md'] }],
    sources: nasty,
    generator: 'g',
    generatedAt: '2026-09-14',
  });

  // Every pipe inside a cell is escaped, and no escaped backslash is left
  // standing in front of a live pipe (which would split the row in two).
  assert.match(row, /\| Windows path C:\\\\ \\\| and a pipe \|/);
  assert.match(row, /\| \[A \\\| B\]\(d.md\) \| ends with a backslash \\\\ \| 1 \|/);
  for (const line of row.split('\n').filter((candidate) => candidate.startsWith('| ['))) {
    assert.equal(line.replace(/\\\\/g, '').split('\\|').join('').split('|').length - 1, 4, `${line} keeps its four cell borders`);
  }
});

test('renderOutput and renderDomain escape their source index the same way', () => {
  const nasty = [{ path: 'specs/a.md', title: 'pipe | and backslash \\', kind: 'spec', date: null }];
  const single = renderOutput({ body: 'b', context: { name: 'x' }, sources: nasty, generator: 'g', generatedAt: '2026-09-14' });
  const page = renderDomain({
    body: 'b',
    context: { name: 'x' },
    domain: { slug: 'd', title: 'D', summary: '', sources: ['specs/a.md'] },
    sources: nasty,
    generator: 'g',
    generatedAt: '2026-09-14',
  });
  for (const markdown of [single, page]) {
    assert.match(markdown, /\| pipe \\\| and backslash \\\\ \|/);
  }
});
