import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  DIGEST_SYSTEM,
  SYNTHESIS_SYSTEM,
  buildDigestPrompt,
  buildSynthesisPrompt,
  renderOutput,
} from '../src/prompts.js';

test('buildDigestPrompt wraps each document with its path, kind and date', () => {
  const prompt = buildDigestPrompt([
    { path: 'specs/a.md', kind: 'spec', date: '2026-06-14', title: 'A', text: 'body A' },
    { path: 'plans/b.md', kind: 'plan', date: null, title: 'B', text: 'body B' },
  ]);
  assert.match(prompt, /Digest the following 2 document\(s\)/);
  assert.match(prompt, /<document path="specs\/a.md" kind="spec" date="2026-06-14" title="A">\nbody A\n<\/document>/);
  assert.match(prompt, /date="unknown"/);
});

test('buildSynthesisPrompt carries the language, the repository context and the source inventory', () => {
  const prompt = buildSynthesisPrompt({
    context: { name: 'maggie', description: 'd', entries: ['apps/', 'libs/'], readme: '# maggie' },
    digests: ['### A digest'],
    lang: 'français',
    sources: [{ path: 'specs/a.md', title: 'A', kind: 'spec', date: '2026-06-14' }],
  });
  assert.match(prompt, /retro-documentation of the repository "maggie" in français/);
  assert.match(prompt, /top-level entries: apps\/, libs\//);
  assert.match(prompt, /- specs\/a.md — A \(spec, 2026-06-14\)/);
  assert.match(prompt, /### A digest/);
});

test('buildSynthesisPrompt says so rather than lying when the repository has no README', () => {
  const prompt = buildSynthesisPrompt({
    context: { name: 'x', description: '', entries: [], readme: '' },
    digests: [],
    sources: [],
  });
  assert.match(prompt, /No README found\./);
  assert.match(prompt, /description: none declared/);
});

test('renderOutput frames the body with a regeneration warning and a source index', () => {
  const markdown = renderOutput({
    body: '## Orientation\n\nIt syncs skills.',
    context: { name: 'maggie' },
    sources: [
      { path: 'specs/a.md', title: 'A | with pipe', kind: 'spec', date: '2026-06-14' },
      { path: 'plans/b.md', title: 'B', kind: 'plan', date: null },
    ],
    generator: 'claude-opus-5',
    generatedAt: '2026-09-13',
  });
  assert.match(markdown, /^<!-- Generated by maggie retro-doc\./);
  assert.match(markdown, /# Retro-documentation — maggie/);
  assert.match(markdown, /Reconstructed from 2 design document\(s\) by `claude-opus-5` on 2026-09-13/);
  assert.match(markdown, /## Orientation/);
  assert.match(markdown, /\| 2026-06-14 \| spec \| A \\\| with pipe \| `specs\/a.md` \|/);
  assert.match(markdown, /\| — \| plan \| B \| `plans\/b.md` \|/);
});

test('the system prompts forbid inventing, and pin the structure the document must have', () => {
  assert.match(DIGEST_SYSTEM, /Never invent/);
  assert.match(DIGEST_SYSTEM, /Cite the source path/);
  for (const heading of ['## Orientation', '## Glossary', '## Architecture as designed', '## Decision log',
    '## Invariants', '## How work gets done here', '## Drift and superseded decisions', '## Open questions']) {
    assert.ok(SYNTHESIS_SYSTEM.includes(heading), `the synthesis prompt asks for ${heading}`);
  }
  assert.match(SYNTHESIS_SYSTEM, /Never invent/);
});

test('buildSynthesisPrompt defaults to English when no language is asked for', () => {
  const prompt = buildSynthesisPrompt({
    context: { name: 'x', description: '', entries: [], readme: '' },
    digests: [],
  });
  assert.match(prompt, /in English/);
});
