import { test } from 'node:test';
import assert from 'node:assert/strict';
import copilot from '../../src/renderers/copilot.js';

const base = { name: 'x', description: 'D', body: '# B', source: 'skills/tech/x/SKILL.md' };

test('copilot derives applyTo from globs and uses instructions path', () => {
  const { path, content } = copilot.render({ ...base, globs: ['**/*.ts', '**/*.tsx'] });
  assert.equal(path, '.github/instructions/x.instructions.md');
  assert.equal(
    content,
    '---\ndescription: "D"\napplyTo: "**/*.ts,**/*.tsx"\n---\n\n<!-- Generated by maggie from skills/tech/x/SKILL.md — edit there, not here. -->\n\n# B\n',
  );
});

test('copilot defaults applyTo to ** when globs absent', () => {
  const { content } = copilot.render(base);
  assert.match(content, /applyTo: "\*\*"/);
});

test('copilot id is "copilot"', () => {
  assert.equal(copilot.id, 'copilot');
});
