import { test } from 'node:test';
import assert from 'node:assert/strict';
import cursor from '../../src/renderers/cursor.js';

const base = { name: 'x', description: 'D', body: '# B', source: 'skills/tech/x/SKILL.md' };

test('cursor with globs sets globs and alwaysApply false', () => {
  const { path, content } = cursor.render({ ...base, globs: ['**/*.ts'] });
  assert.equal(path, '.cursor/rules/x.mdc');
  assert.equal(
    content,
    '---\ndescription: "D"\nglobs: "**/*.ts"\nalwaysApply: false\n---\n\n<!-- Generated by maggie from skills/tech/x/SKILL.md — edit there, not here. -->\n\n# B\n',
  );
});

test('cursor without globs sets empty globs and alwaysApply true', () => {
  const { content } = cursor.render(base);
  assert.equal(
    content,
    '---\ndescription: "D"\nglobs: ""\nalwaysApply: true\n---\n\n<!-- Generated by maggie from skills/tech/x/SKILL.md — edit there, not here. -->\n\n# B\n',
  );
});

test('cursor id is "cursor"', () => {
  assert.equal(cursor.id, 'cursor');
});
